// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDj5ctgQFxzIKvYQHdkjmw0yQhIM4YY0fw',
    appId: '1:1076141888612:web:31e58448e2f92cfa5cbb71',
    messagingSenderId: '1076141888612',
    projectId: 'kayla-f4bf0',
    authDomain: 'kayla-f4bf0.firebaseapp.com',
    storageBucket: 'kayla-f4bf0.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCIQtilshQFoC4opNCL6-AL1bHFyPsq-CM',
    appId: '1:1076141888612:android:de52c3194f9012fa5cbb71',
    messagingSenderId: '1076141888612',
    projectId: 'kayla-f4bf0',
    storageBucket: 'kayla-f4bf0.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUd1fY2FClPkqDI0WQPBoZWsp_5kGiA40',
    appId: '1:1076141888612:ios:2f4ec03aee1527485cbb71',
    messagingSenderId: '1076141888612',
    projectId: 'kayla-f4bf0',
    storageBucket: 'kayla-f4bf0.appspot.com',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAUd1fY2FClPkqDI0WQPBoZWsp_5kGiA40',
    appId: '1:1076141888612:ios:2f4ec03aee1527485cbb71',
    messagingSenderId: '1076141888612',
    projectId: 'kayla-f4bf0',
    storageBucket: 'kayla-f4bf0.appspot.com',
    iosBundleId: 'com.example.bookapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDj5ctgQFxzIKvYQHdkjmw0yQhIM4YY0fw',
    appId: '1:1076141888612:web:ed057026ba50a5915cbb71',
    messagingSenderId: '1076141888612',
    projectId: 'kayla-f4bf0',
    authDomain: 'kayla-f4bf0.firebaseapp.com',
    storageBucket: 'kayla-f4bf0.appspot.com',
  );
}
